{% set name = "slicer" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slicer-{{ version }}.tar.gz
  sha256: a0c868f0a9d453abf439418e8c18808dfbe8ed3ca8c76d661d1aa59764bad7c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - slicer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/interpretml/slicer
  summary: A small package for big slicing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slundberg
