{% set name = "slicer" %}
{% set version = "0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slicer-{{ version }}.tar.gz
  sha256: 8c0fe9845056207d7344d5850e93551f9be20656178d443332aa02da9c71ba44

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - slicer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/interpretml/slicer
  summary: A small package for big slicing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slundberg
