{% set name = "slicer" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slicer-{{ version }}.tar.gz
  sha256: f5d5f7b45f98d155b9c0ba6554fa9770c6b26d5793a3e77a1030fb56910ebeec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - slicer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/interpretml/slicer
  summary: A small package for big slicing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slundberg
    - connortann
    - paulbkoch

